version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r Module-1/Class-3/requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip Module-1/Class-3/lambda_function.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://aws-de-m1-c3-a1/Lambda_Build/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name aws-de-m1-c3-a1-lambda --s3-bucket aws-de-m1-c3-a1 --s3-key Lambda_Build/deployment_package.zip
      - echo "Deployment complete!"